In [1]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randint(0,10, (3,5)),
                columns=["a", "b", "c", "d", "e"])
display(df)
display(df.loc[:, "b":"d"])
display(df.iloc[2, 3])

   a  b  c  d  e
0  7  0  4  6  5
1  5  4  7  5  5
2  7  4  2  1  1

   b  c  d
0  0  4  6
1  4  7  5
2  4  2  1

np.int32(1)