In [3]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randint(0,10, (3,5)),
                columns=["a", "b", "c", "d", "e"])
display(df)
display(df[["a", "c"]])
display(df.filter(regex="b"))

   a  b  c  d  e
0  2  8  0  0  1
1  5  7  8  9  5
2  6  8  3  9  3

   a  c
0  2  0
1  5  8
2  6  3

   b
0  8
1  7
2  8