In [1]:
import numpy as np
import pandas as pd
df=pd.DataFrame({"A":[2,1,5], "B":[3,5,6], "C":[3,6,8]})
df=df.drop(1)
display(df)
df=df.reset_index(drop=True)
df

   A  B  C
0  2  3  3
2  5  6  8

   A  B  C
0  2  3  3
1  5  6  8